# Generated by Django 2.0.2 on 2019-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', to='blog.Tag', verbose_name='标签'),
        ),
    ]
